$('#silder_wrap').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    autoplay:true,
    autoplayTimeout:5000,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
})
$('#slide1').owlCarousel({
    loop:true,
    margin:20,
    nav:true,
    autoplay:true,
    autoplayTimeout:4000,
    responsive:{
        0:{
            items:1
        },
        500:{
            items:2
        },
        768:{
            items:3
        },
        1000:{
            items:4
        }
    }
})
$('#slide2').owlCarousel({
    loop:true,
    margin:20,
    nav:true,
    autoplay:true,
    autoplayTimeout:5000,
    responsive:{
        0:{
            items:1
        },
        500:{
            items:2
        },
        768:{
            items:3
        },
        1000:{
            items:4
        }
    }
})
$('#slide3').owlCarousel({
    loop:true,
    margin:20,
    nav:true,
    autoplay:true,
    autoplayTimeout:4000,
    responsive:{
        0:{
            items:1
        },
        500:{
            items:2
        },
        768:{
            items:3
        },
        1000:{
            items:4
        }
    }
})
$('#slide4').owlCarousel({
    loop:true,
    margin:20,
    nav:true,
    autoplay:true,
    autoplayTimeout:5000,
    responsive:{
        0:{
            items:1
        },
        500:{
            items:2
        },
        768:{
            items:3
        },
        1000:{
            items:4
        }
    }
})
$('#slide5').owlCarousel({
    loop:true,
    margin:20,
    nav:true,
    autoplay:true,
    autoplayTimeout:5000,
    responsive:{
        0:{
            items:1
        },
        500:{
            items:2
        },
        768:{
            items:3
        },
        1000:{
            items:4
        }
    }
})
$('#slide6').owlCarousel({
    loop:true,
    margin:20,
    nav:true,
    autoplay:true,
    autoplayTimeout:3000,
    responsive:{
        0:{
            items:1
        },
        500:{
            items:2
        },
        768:{
            items:3
        },
        1000:{
            items:4
        }
    }
})
$('#qqqr').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    autoplay:false,
    responsive:{
        0:{
            items:2
        },
        768:{
            items:3
        },
        1000:{
            items:4
        }
    }
})
